[tool.poetry]
name = "wapdc"
version = "0.1.0"
description = ""
authors = ["GGOMESSANTOS <160145552+GGOMESSANTOS@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
